---
- hosts: localhost
  connection: local
  remote_user: ayush19
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - sample.users
  vars:
    userList:
      - username: ayush_0119
        password: "gci_ayush"
        shell: /bin/bash
